In [1]:
# 缺失值的处理
#nan:not a number(如无穷大和无穷小无法用数字表示的)
#None:不存在
#pd.NA:不存在，（倾向于没有数值）
import pandas as pd
import numpy as np

s = pd.Series([12,25,np.nan,None,pd.NA])
df = pd.DataFrame([[1,pd.NA,2],[2,3,5],[None,4,6]],columns=['第一列','第二列','第三列'])
print(s)

#查看是否是缺失值(Series中的缺失值)
print(s.isna())
print(s.isnull())

#查看是否是缺失值(DataFrame中的缺失值)
print(df.isna())
print(df.isnull())

print(df.isna().sum(axis=1))#查看缺失值个数(按照行看)
print(df.isnull().sum())#查看缺失值个数(按照列看)
print('-'*30)
#剔除缺失值
print(s.dropna())

print('-'*30)
print(df)
print(df.dropna())#在DataFrame中只要一个index行中存在缺失值,直接整条删除

#如果存在有不想删的(dataFrame中)
print(df.dropna(how='all'))#如果每行所有的值均为缺失值,才删去这一行
print(df.dropna(thresh=2))#如果每行至少有n个(这里为2)不是缺失值就保留
print(df.dropna(thresh=3))
print(df.dropna(axis=1))#剔除一整列的记录
print(df.dropna(subset=['第一列']))#如果某列有缺失值，则删除此列的该位置对应行

#填充缺失值
df = pd.read_csv('data/weather_withna.csv')
df.tail()
df.isna().sum(axis=0)
df.head()
print(df.fillna({'temp_max':20,'wind':2.5}).tail())#使用字典来填充
print(df.fillna(df[['temp_max','wind']].mean()).tail())#使用统计值来填充
print(df.ffill().tail())#用前面的相邻值进行添加front
print(df.bfill().tail())#用后面的相邻值进行填充behind

0      12
1      25
2     NaN
3    None
4    <NA>
dtype: object
0    False
1    False
2     True
3     True
4     True
dtype: bool
0    False
1    False
2     True
3     True
4     True
dtype: bool
     第一列    第二列    第三列
0  False   True  False
1  False  False  False
2   True  False  False
     第一列    第二列    第三列
0  False   True  False
1  False  False  False
2   True  False  False
0    1
1    0
2    1
dtype: int64
第一列    1
第二列    1
第三列    0
dtype: int64
------------------------------
0    12
1    25
dtype: object
------------------------------
   第一列   第二列  第三列
0  1.0  <NA>    2
1  2.0     3    5
2  NaN     4    6
   第一列 第二列  第三列
1  2.0   3    5
   第一列   第二列  第三列
0  1.0  <NA>    2
1  2.0     3    5
2  NaN     4    6
   第一列   第二列  第三列
0  1.0  <NA>    2
1  2.0     3    5
2  NaN     4    6
   第一列 第二列  第三列
1  2.0   3    5
   第三列
0    2
1    5
2    6
   第一列   第二列  第三列
0  1.0  <NA>    2
1  2.0     3    5
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            NaN      20.0       NaN   2.5     NaN
1457  2015-12-28            NaN      20.0       NaN   2.5     NaN
1458  2015-12-29            NaN      20.0       NaN   2.5     NaN
1459  2015-12-30            NaN      20.0       NaN   2.5     NaN
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
            date  precipitation   temp_max  temp_min      wind weather
1456  2015-12-27            NaN  15.851468       NaN  3.242055     NaN
1457  2015-12-28            NaN  15.851468       NaN  3.242055     NaN
1458  2015-12-29            NaN  15.851468       NaN  3.242055     NaN
1459  2015-12-30            NaN  15.851468       NaN  3.242055     NaN
1460  2015-12-31           20.6  12.200000       5.0  3.800000    rain
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27            0.0      11.1       4.4   4.8     sun
1457  2015-12-28            0.0      11.1       4.4   4.8     sun
1458  2015-12-29            0.0      11.1       4.4   4.8     sun
1459  2015-12-30            0.0      11.1       4.4   4.8     sun
1460  2015-12-31           20.6      12.2       5.0   3.8    rain
            date  precipitation  temp_max  temp_min  wind weather
1456  2015-12-27           20.6      12.2       5.0   3.8    rain
1457  2015-12-28           20.6      12.2       5.0   3.8    rain
1458  2015-12-29           20.6      12.2       5.0   3.8    rain
1459  2015-12-30           20.6      12.2       5.0   3.8    rain
1460  2015-12-31           20.6      12.2       5.0   3.8    rain

In [5]:
import pandas as pd
data = {
    "name":['alice','alice','bob','alice','jack','bob'],
    "age":[26,25,30,25,35,30],
    "city":['NY','NY','LA','NY','SY','LA']
}

df = pd.DataFrame(data)
df

    name  age city
0  alice   26   NY
1  alice   25   NY
2    bob   30   LA
3  alice   25   NY
4   jack   35   SY
5    bob   30   LA

In [15]:
df.duplicated()#一整条记录都与前面相同，则标记为重复，返回Ture
df.drop_duplicates(subset=['name'])#根据指定列去重
df.drop_duplicates(subset=['name'],keep='last')#保留最后一次出现的行

    name  age city
3  alice   25   NY
4   jack   35   SY
5    bob   30   LA

In [72]:
#数据类型的转换
df = pd.read_csv('data/sleep.csv')
df

,person_id,gender,age,occupation,sleep_duration,sleep_quality,physical_activity_level,stress_level,bmi_category,blood_pressure,heart_rate,daily_steps,sleep_disorder
0,1,Male,29,Manual Labor,7.4,7.0,41,7,Obese,124/70,91,8539,NaN
1,2,Female,43,Retired,4.2,4.9,41,5,Obese,131/86,81,18754,NaN
2,3,Male,44,Retired,6.1,6.0,107,4,Underweight,122/70,81,2857,NaN
3,4,Male,29,Office Worker,8.3,10.0,20,10,Obese,124/72,55,6886,NaN
4,5,Male,67,Retired,9.1,9.5,19,4,Overweight,133/78,97,14945,Insomnia
...,...,...,...,...,...,...,...,...,...,...,...,...,...
395,396,Female,36,Student,4.5,7.9,73,7,Normal,118/66,64,14497,Sleep Apnea
396,397,Female,45,Manual Labor,6.0,6.1,72,8,Obese,132/80,65,12848,Insomnia
397,398,Female,30,Student,5.3,6.5,58,10,Obese,125/76,66,15255,Insomnia
398,399,Female,41,Retired,11.0,9.1,73,9,Obese,130/75,75,6567,Sleep Apnea
399,400,Male,37,Retired,5.8,7.0,41,6,Normal,118/70,51,18079,NaN

In [48]:
df['age'] = df['age'].astype('int16')
df.dtypes

0        Male
1      Female
2        Male
3        Male
4        Male
        ...
395    Female
396    Female
397    Female
398    Female
399      Male
Name: gender, Length: 400, dtype: category
Categories (2, object): ['Female', 'Male']

In [56]:
df['gender'] = df['gender'].astype('category')

In [60]:
df.gender

0        Male
1      Female
2        Male
3        Male
4        Male
        ...
395    Female
396    Female
397    Female
398    Female
399      Male
Name: gender, Length: 400, dtype: category
Categories (2, object): ['Female', 'Male']

In [76]:
df['is_male'] = df['gender'].map({'Female':True,'Male':False})#map用法,做映射用

In [78]:
df.is_male

0      False
1       True
2      False
3      False
4      False
       ...
395     True
396     True
397     True
398     True
399    False
Name: is_male, Length: 400, dtype: bool

In [150]:
#数据变形
import pandas as pd
data ={
    'ID':[1,2],
    'name':['alice smith','bob smith'],
    'Math':[90,85],
    'English':[88,92],
    'Science':[95,89]
}
df = pd.DataFrame(data)
#分列
df[['first','last']]=df['name'].str.split(" ",expand=True)
df = pd.read_csv('data/sleep.csv')
df.head()
df[['blood_pressure_high','blood_pressure_low']] = df['blood_pressure'].str.split("/",expand=True)

df['blood_pressure_high']=df['blood_pressure_high'].astype('int16')
df['blood_pressure_low']=df['blood_pressure_low'].astype('int16')
df.info()
df.blood_pressure_high.mean()
df.blood_pressure_low.mean()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 15 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   person_id                400 non-null    int64
 1   gender                   400 non-null    object
 2   age                      400 non-null    int64
 3   occupation               400 non-null    object
 4   sleep_duration           400 non-null    float64
 5   sleep_quality            400 non-null    float64
 6   physical_activity_level  400 non-null    int64
 7   stress_level             400 non-null    int64
 8   bmi_category             400 non-null    object
 9   blood_pressure           400 non-null    object
 10  heart_rate               400 non-null    int64
 11  daily_steps              400 non-null    int64
 12  sleep_disorder           110 non-null    object
 13  blood_pressure_high      400 non-null    int16
 14  blood_pressure_low       400 non-null    int16
dtypes: float64(2), int16(2), int64(6), object(5)
memory usage: 42.3+ KB

73.04

In [116]:
df.T #行列转置
df
'''
ID name  科目 成绩
1 alice Math 90
1 alice English 88
1 alice Science 95
'''

#宽表转换为长表
df2 = pd.melt(df,id_vars=['ID','name'],var_name='科目',value_name='分数')
df2.sort_values('name')

   ID   name       科目  分数
0   1  alice     Math  90
2   1  alice  English  88
4   1  alice  Science  95
1   2    bob     Math  85
3   2    bob  English  92
5   2    bob  Science  89

In [152]:
#长表转宽表
pd.pivot(df2,index=['ID','name'],columns='分数',values='科目')

分数          85       88       89    90       92       95
ID name
1  alice   NaN  English      NaN  Math      NaN  Science
2  bob    Math      NaN  Science   NaN  English      NaN

In [161]:
#数据分箱 pd.cut(x,bins,labels)

import pandas as pd

df = pd.read_csv('data/employees.csv')
df.head(10)

,employee_id,first_name,last_name,email,phone_number,job_id,salary,commission_pct,manager_id,department_id
0,100,Steven,King,SKING,515.123.4567,AD_PRES,24000.0,NaN,NaN,90.0
1,101,N_ann,Kochhar,NKOCHHAR,515.123.4568,AD_VP,17000.0,NaN,100.0,90.0
2,102,Lex,De Haan,LDEHAAN,515.123.4569,AD_VP,17000.0,NaN,100.0,90.0
3,103,Alexander,Hunold,AHUNOLD,590.423.4567,IT_PROG,9000.0,NaN,102.0,60.0
4,104,Bruce,Ernst,BERNST,590.423.4568,IT_PROG,6000.0,NaN,103.0,60.0
5,105,David,Austin,DAUSTIN,590.423.4569,IT_PROG,4800.0,NaN,103.0,60.0
6,106,Valli,Pataballa,VPATABAL,590.423.4560,IT_PROG,4800.0,NaN,103.0,60.0
7,107,Diana,Lorentz,DLORENTZ,590.423.5567,IT_PROG,4200.0,NaN,103.0,60.0
8,108,Nancy,Greenberg,NGREENBE,515.124.4569,FI_MGR,12000.0,NaN,101.0,100.0
9,109,Daniel,Faviet,DFAVIET,515.124.4169,FI_ACCOUNT,9000.0,NaN,108.0,100.0

In [173]:
df1 = df.head(10)[['employee_id','salary']]
df1

   employee_id   salary
0          100  24000.0
1          101  17000.0
2          102  17000.0
3          103   9000.0
4          104   6000.0
5          105   4800.0
6          106   4800.0
7          107   4200.0
8          108  12000.0
9          109   9000.0

In [201]:
pd.cut(df1['salary'],bins=2) #bins=n ,及分成n段区间,起始值、结束值是所有数据的最小值和最大值
#4180~14100~24000
pd.cut(df1['salary'],bins=3).value_counts()
pd.cut(df1['salary'],bins=[0,10000,20000,30000]).value_counts()#bins=list,分成n段区间
df1['收入范围']=pd.cut(df1['salary'],bins=[0,10000,20000,30000],labels=['低','中','高'])
pd.qcut(df1['salary'],3).value_counts()#按人数区分划分，等频率划分

salary
(12000.0, 24000.0]    4
(4199.999, 6000.0]    3
(6000.0, 12000.0]     3
Name: count, dtype: int64

In [249]:
#睡眠数据
import pandas as pd

df = pd.read_csv('data/sleep.csv')
df.head(10)

df1 = df.head(10)[['person_id','sleep_quality']]
df1
df['睡眠质量']=pd.cut(df['sleep_quality'],bins=3,labels=['差','中','优'])
df['睡眠质量'].value_counts()
df.head(10)
df['gender']=df['gender'].astype('category')
df['gender'].value_counts()
#字符串-->类别-->统计
#数值-->分箱-->统计
print(df['gender'].dtype)
print(df['睡眠质量'].dtype)

category
category

In [269]:
# df.rename() df.set_index() df.reset_index()
df = pd.DataFrame(
    {
        'name':['jack','alice','tom','bob'],
        'age':[20,30,40,50],
        'gender':['female','male','female','male']
    }
)
df.set_index('name',inplace=True)#inplace:作用于该数据框（df此DataFrame上）
df.reset_index(inplace=True)
df.rename(columns={"age":"年龄"},index={0:4})#{老：新}

    name  年龄  gender
4   jack  20  female
1  alice  30    male
2    tom  40  female
3    bob  50    male

In [279]:
#直接通过属性进行赋值
df.index=[1,2,3,4]
df.columns=["姓名","年龄","性别"]
df

      姓名  年龄      性别
1   jack  20  female
2  alice  30    male
3    tom  40  female
4    bob  50    male

In [281]:
#时间数据的处理
import pandas as pd